/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Collapse: typeof import('./components/DataDisplay/Collapse.vue')['default']
    CommonTabs: typeof import('./components/Navigation/CommonTabs.vue')['default']
    ConcretServerInfo: typeof import('./components/ConcretServerInfo.vue')['default']
    CQMUServerInformation: typeof import('./components/CQMUServerInformation.vue')['default']
    CYMCServerStatus: typeof import('./components/CYMCServerStatus.vue')['default']
    ElAvatar: typeof import('element-plus/es')['ElAvatar']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElCollapse: typeof import('element-plus/es')['ElCollapse']
    ElCollapseItem: typeof import('element-plus/es')['ElCollapseItem']
    ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
    ElDescriptions: typeof import('element-plus/es')['ElDescriptions']
    ElDescriptionsItem: typeof import('element-plus/es')['ElDescriptionsItem']
    ElDivider: typeof import('element-plus/es')['ElDivider']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElImage: typeof import('element-plus/es')['ElImage']
    ElLink: typeof import('element-plus/es')['ElLink']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElPopover: typeof import('element-plus/es')['ElPopover']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
    ElSkeleton: typeof import('element-plus/es')['ElSkeleton']
    ElSkeletonItem: typeof import('element-plus/es')['ElSkeletonItem']
    ElSpace: typeof import('element-plus/es')['ElSpace']
    ElSubMenu: typeof import('element-plus/es')['ElSubMenu']
    ElTag: typeof import('element-plus/es')['ElTag']
    Footer: typeof import('./components/layouts/Footer.vue')['default']
    FrontInfo: typeof import('./components/FrontInfo.vue')['default']
    Header: typeof import('./components/layouts/Header.vue')['default']
    InfiniteScroll: typeof import('./components/DataDisplay/InfiniteScroll.vue')['default']
    Logos: typeof import('./components/Logos.vue')['default']
    MUAServers: typeof import('./components/MUAServers.vue')['default']
    ServerStatistic: typeof import('./components/ServerStatistic.vue')['default']
    Side: typeof import('./components/layouts/Side.vue')['default']
    SingleSiteServer: typeof import('./components/SingleSiteServer.vue')['default']
    Skeleton: typeof import('./components/Skeleton.vue')['default']
    StatusUpdate: typeof import('./components/StatusUpdate.vue')['default']
  }
  export interface ComponentCustomProperties {
    vLoading: typeof import('element-plus/es')['ElLoadingDirective']
  }
}
